### ISSUE TITLE
Exercise inner sends with a custom actor

### ISSUE THREAD

**Issue by anorth** [filecoin-project/chain-validation#131]
To further exercise inner sends we need a new actor through which we can invoke Runtime.Send() without actor-level validation getting in the way. We wouldn't install this actor in real chains, only for testing.

We might be able to put that actor in this repo, or possibly the specs-actors repo if necessary.

**Comment by frrist** [comment]
]The current nested sends tests should be modified to use the custom actor as part of completing this issue. Note the comment at the bottom of the nested sends test file for future test cases.
