### ISSUE TITLE
Write documentation for RPC API

### ISSUE THREAD

**Issue by frrist** [filecoin-project/chain-validation#165]
The RPC client added in https://github.com/filecoin-project/chain-validation/pull/155 needs API documentation. Documentation should cover:
- link to design doc
- complete json RPC API reference
  - Parameters
  - Example Parameters
  - Returns
  - Example (a request and its result)
- how to use the client as a test runner
  - env vars for configuring connections
  - validation config
  - `go test` to run.

**Comment by raulk** [comment]
RPC-related tasks are not relevant any longer with the new [test-vector-driven approach](https://github.com/filecoin-project/test-vectors). Closing this to groom the backlog.
