### ISSUE TITLE
[spike] Improve pattern of resource generation

### ISSUE THREAD

**Issue by frrist** [filecoin-project/chain-validation#190]
As a follow on to https://github.com/filecoin-project/chain-validation/pull/188 we should look for a better resource generation pattern that does not require chain-validation tests to follow a [specific naming pattern](https://github.com/filecoin-project/chain-validation/pull/188/files#diff-feda8d481b946224f2b1805bbad9ba20R103).

**Comment by raulk** [comment]
No longer required.
